## Đọc dữ liệu
library(dplyr)
library(tidyr)
old_data <- read.csv("usa.csv")
## Làm sạch dữ liệu (Data cleaning)
new_data <- old_data %>% select(3:14)

### Trích xuất các dữ liệu chính
#(Chỉ giữ lại các cột cần thiết, bao gồm 6 cột của biến dự đoán và cột biến ước lượng)
main_data <- subset(new_data , select = c(new_deaths , new_cases , new_tests , icu_patients , hosp_patients , people_fully_vaccinated , positive_rate))

### Xử lý dữ liệu khuyết (NA)
#(Kiểm tra các dữ liệu NA, thay bằng 0 hoặc giá trị khác)
main_data %>% sapply(function(col) sum(is.na(col)))    #Số dữ liệu bị khuyết theo cột
apply(main_data, 2, function(x)sum(is.na(x))/length(x))    #Tỉ lệ dữ liệu bị khuyết
main_data[is.na(main_data)] <- 0    #NA <- 0

## Làm rõ dữ liệu
## Chuyển đổi biến (Data transformation)
Chuyển qua logarithm hoặc các dạng khác nếu cần.
## Thống kê mô tả
### Thống kê đơn biến
Thực hiện các phương pháp thống kê đơn biến lên từng biến dự đoán, 1 vài phương pháp: Summary Statistics, Frequency Distribution Table, Bar chart, Histogram... 

### Thống kê đa biến
Tính ma trận hiệp phương sai (matrix 7x7)

Dựng đồ thị mô tả sự tương quan giữa các biến

# Xây dựng mô hình hồi quy bội
## Định nghĩa và ký hiệu cho mô hình

## Ước lượng tham số
Tính ra các hệ số của mô hình

## Ước lượng độ lệch chuẩn của sai số

## Xác định hệ số $R^2$ hiệu chỉnh

## Xác định khoảng tin cậy của các hệ số hồi quy

## Kiểm định đường hồi quy và các hệ số hồi quy

## Xác định khoảng tin cậy của giá trị trung bình của $Y$ khi $x=x_0$

## Xác định khoảng tin cậy của các giá trị dự đoán

## Kiểm định sự phù hợp của mô hình hồi quy tuyến tính